### ISSUE TITLE
[FEAT] 실험을 해보자!

### ISSUE THREAD

**Issue by minseokheo** [boostcampaitech7/level2-objectdetection-cv-21#121]
## Background
- 가장 빠른 모델인 faster_rcnn_resnet50 모델에 남규님의 가설을 바탕으로 추가 실험을 주문해 주셨습니다

## Todo
- [x] test_config에 miniourandomcrop 추가 실험
- [x] test_config에 1024사이즈로 실험
- [x] test_config에 horizontalflip을 빼고 실험
