### ISSUE TITLE
[FEAT] 기본 코드 이외의 빠른 학습을 위한 detectron2 전용 스크립트 추가

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level2-objectdetection-cv-21#16]
## Background
- 기존 코드가 동작하고 있지 않으나, 새로고침 기간 동안에 학습할 코드가 필요함

## Todo
- [ ] detectron2를 활용한 학습 스크립트 추가
- [ ] detectron2에 쓰이는 모델 config 파일 추가
- [ ] (가능하면) mmdetection dependency 확인 및 버전 최신화

## See also
- #14
