### ISSUE TITLE
[FEAT] Pipeline  최적화 : Config, Requirments

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-objectdetection-cv-21#22]
## Background
- MMDetection, Detectron2 모델은 추가되었지만, "config, requirments" 부분이 지저분하게 배치되어 있습니다.
- 앞으로 만들 train.py를 단순화하기 위해서, cfg 부분을 보다 명확하게 하는 것이 핵심입니다.
- 따라서 관련된 내용들을 읽고 Refactorization을 하는 것이 최종 목표입니다.

## Todo
- [ ] [MMDetection config user guide](https://github.com/open-mmlab/mmdetection/blob/main/docs/en/user_guides/config.md)를 읽고, 전체적인 구조의 흐름 이해하기
- [ ] 현재 Pipeline에서 MMDetection cfg를 이용하도록 다듬기
- [ ] "utils" 폴더에 있는 WanDB login 부분을 모델에서 이용하도록 코드 수정하기
- [x] #28

## See also
-
