### ISSUE TITLE
[FEAT] TIP: Tabular-Image Pre-training

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level2-objectdetection-cv-21#36]
## Background
-Object Detection에서 탭형 데이터와의 융합
객체 탐지에서는 특정 클래스의 객체가 다른 클래스보다 빈도가 낮아 클래스 불균형이 큰 문제로 작용할 수 있습니다. 이 경우, 탭형 데이터(메타데이터)에서 얻을 수 있는 정보는 보조 손실을 통해 모델이 부족한 데이터를 보충하는 데 유효할 수 있습니다.
객체 탐지에서 이미지의 시각적 정보만으로는 모델이 학습하기 어려운 컨텍스트 정보를 제공할 수 있습니다. 
탭형 데이터에서 객체의 위치와 관련된 정보를 활용하면, 모델이 보다 정확한 바운딩 박스를 예측하는 데 도움을 줄 수 있습니다. 예를 들어, 특정 유형의 쓰레기는 항상 특정 위치에 놓일 수 있습니다. 이러한 정보를 모델이 학습하게 되면, 위치 기반 탐지가 더 효과적일 수 있습니다.

## Todo
- [ ] 탭형 데이터 예측 보조 손실 추가
- [ ] 자가 지도 학습을 통한 사전 학습 (Pre-training)
- [ ] Fine-Tuning 이미지 모델

## See also
- TIP: Tabular-Image Pre-training for Multimodal Classification with Incomplete Data (ECCV 2024): 이미지와 탭형 데이터를 결합한 멀티모달 학습을 효과적으로 수행하는 기법을 소개한 논문으로, 이번 프로젝트에서 자가 지도 학습과 탭형 데이터 보조 손실 기법을 도입하는 데 참고할 수 있습니다.
