### ISSUE TITLE
[FEAT] EDA 분석 결과를 Streamlit 앱으로 배포

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level2-objectdetection-cv-21#45]
## Background
- 분리수거 데이터의 EDA를 통해 데이터의 특성을 파악하고, 주요 인사이트를 얻기 위함.
- 주로 데이터의 분포, 클래스 불균형 문제 등을 확인.

## Todo
- [ ] 간단한 Streamlit 앱 템플릿 설정 (예: streamlit run app.py로 실행)
- [x] pandas 라이브러리로 JSON 파일 불러오기: pd.read_json('파일경로')
- [ ] JSON 구조에 따라 필요한 데이터 파싱 및 정리
- [ ] 결측치가 있을 경우 처리 방법 결정 (object 40개 이상)
- [ ] bar chart, pie chart 등을 사용해 각 클래스의 분포 확인
- [x] 클래스 불균형 문제 확인
- [x] Box plot 또는 scatter plot으로 데이터의 이상치(Outliers) 확인
- [ ] 완성된 EDA 분석 결과를 Streamlit 앱으로 배포
