### ISSUE TITLE
[FEAT] 개발 환경을 Cloud 기반으로 전환하기

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-objectdetection-cv-21#48]
## Background
# SSH 개발 환경 (현재)
- 지금 개발 환경은 독립된 4개의 SSH 서버에서 각각의 리소스(gpu)를 할당하는 방식입니다.
- pros : 각각의 서버에 고정된 리소스를 제공합니다.
- cons : gpu의 유동성이 부족합니다. 

# Cloud 개발 환경 (목표)
- Cloud system에서는 독립된 서버들을 병합하고, 리소스를 자동 분배해주는 작업이 가능합니다. (ex. Google Cloud : Managed Instance Group)
- 이는 확장성 및 유동성에 있어서 SSH 서버보다 엄청난 장점이 있다고 생각합니다.

# Conclusion
- 따라서 개발 환경을 현재의 SSH 환경에서 Cloud 기반으로 옮겨보고 싶습니다.
- AWS, Google, Azure 등 다양한 Cloud system이 존재하지만, 이번 프로젝트에서는 우선 Google Cloud를 도입해보고 싶습니다.
-> Why? : Google Cloud는 체험판 gpu를 제공해줘서, MMDetection v3.2.0처럼 기존에 버전 이슈 때문에 해볼 수 없던 작업이 가능할 것이라 기대됩니다. 

## Todo
- [ ] Google cloud 학습하기 ([Lecture LINK](https://www.youtube.com/live/m6ozQnqit50?si=DwfbdZPB6bJKeSuk))
- [ ] SSH 개발 환경을 Cloud system으로 옮기기
- [ ] (Optional) Docker를 활용해 container 작업 환경 구축하기

## See also
- Booscamp 5th CV : Final Project Pipeline ([URL](https://github.com/boostcampaitech5/level3_cv_finalproject-cv-15?tab=readme-ov-file))
- GCP docs : Instance Group ([URL](https://cloud.google.com/compute/docs/instance-groups?hl=ko))
- GCP docs : Terraform ([URL](https://cloud.google.com/docs/terraform?hl=ko))
![image](https://github.com/user-attachments/assets/27bbae3a-3703-4f36-906d-907f48ee0abb)
- MIG(Managed Instance Group) + Load Balancer = SSH 자동 분배(!!)
