### ISSUE TITLE
[FEAT] Ray 분산 시스템 도입

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-objectdetection-cv-21#53]
## Background
- 이전에 언급 했듯이, 리소스 자동 분배 시스템을 구축해보고 싶습니다.
- 시스템을 도입하기 위한 도구로 Google Cloud 대신 Ray를 이용하는 것으로 목표를 수정합니다.

## Todo
- [ ] Ray script file 작성
- [ ] 서버에서 Ray가 정상적으로 작동하는지 확인
- [ ] (Optional) Docker 파일 추가

## See also
- #48
