### ISSUE TITLE
[FEAT] 서버 내의 폴더 이름 통합하기

### ISSUE THREAD

**Issue by minseokheo** [boostcampaitech7/level2-objectdetection-cv-21#66]
## Background
- 서버 내에서 개인 폴더를 사용하면서 개인 폴더 안에서 동일한 repository를 remote하는 번거로움이 생김
- 서버는 개인공간이 아니기에..(1인 1GPU) 누구나 언제든지 사용할 수 있으면 좋겠다고 생각함!

## Todo
- [x] 각 서버내의 폴더명 바꾸기 (이름 -> github) 
- [x] how_to_setup_and_train_kor.mid 내의 서버 초기설정 방법 수정
- [x] inference.py 내의 경로 수정

## Check
- 서버가 터진 후 새로 설치하실 때 꼭 반영 부탁드립니다~!
