### ISSUE TITLE
[FEAT] Set up YOLOv11x

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level2-objectdetection-cv-21#72]
## Background
- YOLOv11x 모델을 사용하여 object detection
- Ultralytics의 YOLOv11x 모델을 클론하여 설치하고, 이를 프로젝트에 통합하는 과정을 관리하는 이슈

## Todo
- [x] Ultralytics repo에서 YOLOv11x 모델 클론
- [x] 파이프라인 구축
- [x] YOLOv11x를 실행하기 위한 라이브러리 설치
- [x] Set up YOLOv11x model
- [ ] 성능 테스트 및 평가

## See also
- [YOLO11 Repo](https://github.com/ultralytics/ultralytics)
- [docs](https://docs.ultralytics.com/)
