### ISSUE TITLE
[FEAT] Online vs Offline Augmentation

### ISSUE THREAD

**Issue by Namgyu-Youn** [boostcampaitech7/level2-objectdetection-cv-21#79]
## Background
Augmentation을 흥미로운 가설들을 세우면서 적용시켰던 이전 기수 분들이 있어, 지금 프로젝트에 적용해보고 싶습니다.

1. Background : Online vs Offline Augmentation
- Online : Pure Dataset만을 이용해서 편집하는 작업을 수행하는 기법을 의미합니다. (ex. Crop, Flip, ColorFilter)
- Offline : Pure Dataset을 이용해서 새로운 sample(data)를 만들어내고, 이를 모델 학습에 적용시키는 기법을 의미합니다. (ex. Diffusion, TTA)

2. 해당 프로젝트에서 특이한 점 : Augmentation에 대한 가설 세우기
- Ex 1. 만약 어떤 image가 다양한 Viewpoint에서 관측되기 좋은 경우 : Geometric Transform(ex. Flip, Rotate)을 수행했을 때 성능 향상이 있을 것이다.
- Ex 2. Color spectrum이 넓은 image인 경우 : Spectrum을 좁혔을 때, 성능 향상이 있을 것인가?
- Ex 3. Sample size가 매우 적은 Category인 경우 : Mosaic를 적용시키면 증강 효과를 기대해볼 수 있을 것이다.

## Todo
- [ ] 5기 3조 분들의 Augmentation 부분을 코드 리뷰하면서, 어떤 방식으로 접근했는지 파악하기
- [ ] Augmenation 가설 세우기
- [ ] 가설을 세운 Augmentation을 재현해보면서 검증해보기

## See also
- [Wrapup Report](https://file.notion.so/f/f/34e15efc-e2be-46ba-ae66-9fe65d825d78/596eb094-e86c-4937-b0b4-ee218fc18952/ObjectDetection_CV_%ED%8C%80%EB%A6%AC%ED%8F%AC%ED%8A%B8(03%EC%A1%B0).pdf?table=block&id=3c24f689-1e07-467a-84de-9e05578daa34&spaceId=34e15efc-e2be-46ba-ae66-9fe65d825d78&expirationTimestamp=1729087200000&signature=D9j-EkmX4cBJZxG8ul_3vQJFZZJBrRpeDK6puvyHngQ&downloadName=ObjectDetection_CV_%ED%8C%80%EB%A6%AC%ED%8F%AC%ED%8A%B8%2803%EC%A1%B0%29.pdf),
- [GitHub : CV 5기-3조](https://github.com/boostcampaitech5/level2_objectdetection-cv-03)
- [StackOverflow : What is Online&Offline Augmentation?](https://stackoverflow.com/questions/72388663/online-vs-offline-data-augmentation)
