### ISSUE TITLE
[FEAT] "Training with multi-crop" 후속 연구 찾아보기

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-objectdetection-cv-21#89]
## Background
1. (Code Review) [multi-crop](https://github.com/boostcampaitech6/level2-objectdetection-cv-01/tree/main)
- EDA 과정에서 "object size가 매우 작은(=background가 너무 넓은)" data가 다수 존재함을 확인함.
- 이를 Center-crop, Multi-crop(4분할) 기법을 각각 수행해본 결과(performance) : multi-crop > center-crop > original
-  뒤에 소개할 논문을 적용해봄으로써, multi-crop(4분할)이 보다 좋은 성능을 보임을 확인함.

2. (Paper Review) [Enhanced Deep Residual Networks for Single Image Super-Resolution](https://arxiv.org/abs/1707.02921)
- 이전에 부스트코스에서 배웠던 내용인데, CNN의 초기 모델들은 "네트워크가 더 넓고 깊어질수록 성능이 좋아질 것이다"를 바탕으로 연구되었습니다. (연산량이 너무 커지면서, 후속 연구들의 방향은 달라졌죠.)
- 이 논문도 비슷한 느낌입니다. "객체의 크기가 작아서 object detection이 힘들다면, image를 더 작게 multi-crop을 하고 학습시킬수록, 성능이 좋아질 것이다."를 입증한 것이 이 논문의 의의 입니다. 
![image](https://github.com/user-attachments/assets/4d68f9e8-cfdb-49e0-bac5-4509c1ec164f)

3. 그런데 해당 논문의 출판 년도가 2017년인 만큼, 후속 연구들이 방대할 것이라고 생각합니다. 따라서 적당한 후속 연구를 찾아보고, 이를 지금 프로젝트에 적용해보는 것이 최종 목표입니다.

## Todo
- [x] Step 1. 적당한 후속 연구 알아보기
- [x] Step 2. "Step 1"의 자료를 구현한 코드 찾기
- [x] Step 3. 이미 구현된 코드를 적당히 변형시켜 지금 프로젝트에 적용 가능하도록 해보기
- [x] Step 4. 해당 기법을 적용시켜보고, 성능 향상이 있는지 확인하기

## See also
- #77 : 민석님이 작업한, multi-cropped dataset 입니다. (아직 모델에 적용해보지는 않았습니다.)
- #90  : Multi-crop을 적용한 경우에 성능 변화를 확인하는 Issue 입니다.
