### ISSUE TITLE
[FEAT] ConvNeXt Model

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level2-objectdetection-cv-21#96]
## Background
- ConvNeXt V2는 Masked Autoencoder(MAE)같은 Self-Supervised Learning 사용하는데요.  사전 학습된 가중치를 재활용 품목 분류에 Transfer Learning을 활용하면 좋을 것 같다는 생각이 들었습니다. 왜냐하면 ConvNeXt V2는 GRN(Global Response Normalization) 레이어를 사용하여 채널 간 특징을 경쟁적으로 학습하기 때문에 저번에 작은 object를 detect할 수 없는 문제가 있었는데, 재활용 품목 간의 미세한 차이를 인식해서 bbox 좌표와 카테고리를 정확하게 예측할 수 있지 않을까요?

## Todo
- [ ] Object Detection task에 맞는 아키텍처로 모델 커스터마이징
- [ ] 모델에 맞는 입력 크기 설정 및 데이터 전처리
- [ ] BBox와 카테고리 정보를 학습할 수 있도록 모델 학습 설정 (Loss 함수 등)

## See also
[ConvNeXt V2](https://arxiv.org/abs/2301.00808)
